### ISSUE TITLE
Cover image not loading in Local source

### ISSUE THREAD

**Issue by uzuto** [Animetailapp/Animetail#123]
### Steps to reproduce

1. Put some media in localanime folder with cover image (.jpg/.png)
2. Open App -> Sources -> Local Anime -> media entry
3. The metadata is loaded but only the cover is not displayed, changing the cover also doesn't work

### Expected behavior

Cover image should be displayed

### Actual behavior

Cover is empty

### Crash logs

I haven't experienced crash but log might come in handy 
[Log.txt](https://github.com/user-attachments/files/16124031/Log.txt)

### Animetail version

App version: 0.16.4.6

### Android version

HyperOS (Android 14)

### Device

Redmi 12C (earth)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
already fixed and available in the next version

**Comment by uzuto** [comment]
Thanks
