### ISSUE TITLE
Descarga desde historial 

### ISSUE THREAD

**Issue by FrankieD777** [Animetailapp/Animetail#133]
### Describe your suggested feature

Es fácil me preguntó si podría agregar una opción de descargar desde el historial como descargar últimas 10 historias/mangas vistas/leídos(o más bien por leer) y tambien la cantidad de capítulos como lo normal por ejemplo estoy leyendo un manga reciente leí 10 capitulo y tiene unos 33 pues le doy a descargar los siguientes 25 capitulos o descargar todo

### Other details

Por favor y muchas gracias 🫂🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Existe una opcion, para descargar automaticamente los capitulos nueovos, te podria servir de igual forma  👍
