### ISSUE TITLE
Eh no sé si esto se consideraría sugerencia para la app o problemas de extensión 

### ISSUE THREAD

**Issue by FrankieD777** [Animetailapp/Animetail#134]
### Describe your suggested feature

Podrían hacer un panel de filtro más estético y útil como una combinación entre los paneles de legión anime y jkanime y si es posible integrarlo en la app y aplicarlo en todas las extensiones por favor pido esto principalmente por extensiones como olympus entre otras que no tienen una forma de navegar muy versátil sin ofender gracias por haber leídos todo esto, espero su respuesta y lo hagan o no muchas gracias por sus servicios 🫂🌹

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Tienes algunas imagenes de  como seria ?

**Comment by FrankieD777** [comment]
![Screenshot_20240729-094021](https://github.com/user-attachments/assets/90928d9e-7e08-44cc-8463-53d4dc877a14)
![Screenshot_20240729-094002](https://github.com/user-attachments/assets/b4834836-66cb-4a41-a367-e2eb13802587)
Pues no puedo hacer una imagen combinada pero estos son los dos paneles creo que están más que completos aunque el de jkanime sobre sale mucho más en opciones

**Comment by Dark25** [comment]
Esto no  depende de nosotros, depende del matenedor del repositorio

**Comment by FrankieD777** [comment]
Pero no sé podría agregar una opción de filtro aunque no sea tan detallada una general o mejor una que analice la extensiones en vivo y generé la opción de filtro personaliza para cada cual :3?

**Comment by Dark25** [comment]
Ahora mismo no, ya que  las extensiones  se programan cada una por separado. Ademas cada web tiene filtros  y formas diferentes 

> Pero no sé podría agregar una opción de filtro aunque no sea tan detallada una general o mejor una que analice la extensiones en vivo y generé la opción de filtro personaliza para cada cual :3?
