### ISSUE TITLE
Buenas creo que encontré un pequeño problema en su app aunque no se si reportarlo como bug

### ISSUE THREAD

**Issue by FrankieD777** [Animetailapp/Animetail#135]
### Steps to reproduce

Simplemente miren 

Aniyomi 
![Screenshot_20240802-114834](https://github.com/user-attachments/assets/a34919b1-79eb-4611-983e-146a20cadd03)
![Screenshot_20240802-114831](https://github.com/user-attachments/assets/829087a8-2151-4331-b3e7-637e2da26eb0)

Su app
![Screenshot_20240802-114949](https://github.com/user-attachments/assets/7db30e0b-1a7d-4422-813e-ab17e9f6914b)

La cosa es simple no hay cambio de ascendente y descenso en animetail ;----;

### Expected behavior

Que si haga descendiente y ascendente 

### Actual behavior

Solo da para un lado xd

### Crash logs

Solo tiene una opción cada filtro XD 

### Animetail version

0.16.5.2

### Android version

Android 14

### Device

TECNO SPARK 10 Pro

### Other details

Arreglenlo por favor y muchas gracias que tengáis un bonito día 💀💐

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
fixed
