### ISSUE TITLE
Video player ceaps crashing 

### ISSUE THREAD

**Issue by Darkdk3** [Animetailapp/Animetail#137]
### Steps to reproduce

Click on the anime you want to watch 

### Expected behavior

When clicking on a episode the anime should start playing 

### Actual behavior

When you try to play a anime the app just kicks you out 

### Crash logs

App version: 0.16.5.2 (standard, f738d5cc, 126, 2024-07-28T22:08:36Z)
Android version: 10 (SDK 29; build ARTH-L29 10.1.0.268(C185E2R3P1))
Android build ID: ARTH-L29 10.1.0.268(C185E2R3P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWART-H (ART-L29)
Device model: ART-L29
WebView: Huawei WebView 12.1.2.323
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

--------- beginning of crash
08-04 06:19:03.197  8096  8096 E AndroidRuntime: FATAL EXCEPTION: main
08-04 06:19:03.197  8096  8096 E AndroidRuntime: Process: com.dark.animetailv2, PID: 8096
08-04 06:19:03.197  8096  8096 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dark.animetailv2/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:66)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.onCreate(Unknown Source:2282)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8085)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8073)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	... 11 more
08-04 06:19:03.197  8096  8096 E AndroidRuntime: Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:44)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zza(Unknown Source:1)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:121)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:55)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	... 16 more
08-04 06:19:03.197  8096  8096 E AndroidRuntime: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:811)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:6)
08-04 06:19:03.197  8096  8096 E AndroidRuntime: 	... 19 more
08-04 06:24:51.272  8659  8659 E AndroidRuntime: FATAL EXCEPTION: main
08-04 06:24:51.272  8659  8659 E AndroidRuntime: Process: com.dark.animetailv2, PID: 8659
08-04 06:24:51.272  8659  8659 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dark.animetailv2/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:66)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.onCreate(Unknown Source:2282)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8085)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8073)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	... 11 more
08-04 06:24:51.272  8659  8659 E AndroidRuntime: Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:44)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zza(Unknown Source:1)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:121)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:55)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	... 16 more
08-04 06:24:51.272  8659  8659 E AndroidRuntime: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:811)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:6)
08-04 06:24:51.272  8659  8659 E AndroidRuntime: 	... 19 more
08-04 06:25:15.099 11186 11186 E AndroidRuntime: FATAL EXCEPTION: main
08-04 06:25:15.099 11186 11186 E AndroidRuntime: Process: com.dark.animetailv2, PID: 11186
08-04 06:25:15.099 11186 11186 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dark.animetailv2/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:66)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.onCreate(Unknown Source:2282)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8085)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8073)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	... 11 more
08-04 06:25:15.099 11186 11186 E AndroidRuntime: Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:44)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zza(Unknown Source:1)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:121)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:55)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	... 16 more
08-04 06:25:15.099 11186 11186 E AndroidRuntime: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:811)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:6)
08-04 06:25:15.099 11186 11186 E AndroidRuntime: 	... 19 more
08-04 06:30:47.192 13424 13424 E AndroidRuntime: FATAL EXCEPTION: main
08-04 06:30:47.192 13424 13424 E AndroidRuntime: Process: com.dark.animetailv2, PID: 13424
08-04 06:30:47.192 13424 13424 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dark.animetailv2/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:66)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.onCreate(Unknown Source:2282)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8085)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8073)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	... 11 more
08-04 06:30:47.192 13424 13424 E AndroidRuntime: Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:44)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zza(Unknown Source:1)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:121)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:55)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	... 16 more
08-04 06:30:47.192 13424 13424 E AndroidRuntime: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:811)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:6)
08-04 06:30:47.192 13424 13424 E AndroidRuntime: 	... 19 more
08-04 06:36:40.360 14203 14203 E AndroidRuntime: FATAL EXCEPTION: main
08-04 06:36:40.360 14203 14203 E AndroidRuntime: Process: com.dark.animetailv2, PID: 14203
08-04 06:36:40.360 14203 14203 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dark.animetailv2/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:66)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.onCreate(Unknown Source:2282)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8085)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8073)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	... 11 more
08-04 06:36:40.360 14203 14203 E AndroidRuntime: Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:44)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zza(Unknown Source:1)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:121)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:55)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	... 16 more
08-04 06:36:40.360 14203 14203 E AndroidRuntime: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:811)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	at com.google.android.gms.internal.cast.zzad.zzf(Unknown Source:6)
08-04 06:36:40.360 14203 14203 E AndroidRuntime: 	... 19 more
--------- beginning of system
--------- beginning of main

### Animetail version

0.16.5.2

### Android version

Android 10

### Device

HUAWEI y7p 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Darkdk3** [comment]
https://github.com/user-attachments/assets/a416066e-1cc5-4cd8-b571-a8728fae996e

**Comment by Dark25** [comment]
fix
