### ISSUE TITLE
Add a monet icon

### ISSUE THREAD

**Issue by ghost** [Animetailapp/Animetail#139]
### Describe your suggested feature

Add a monet icon as it is very vital to the working of the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
added, and available in the new version
