### ISSUE TITLE
Crash on play

### ISSUE THREAD

**Issue by Billiamson** [Animetailapp/Animetail#142]
### Steps to reproduce

App crashes when i try to play any episode, any source, internal or external player.
1. Play episode
2. Crash

### Expected behavior

Shouldn't crash

### Actual behavior

Crashes

### Crash logs

[animetail_crash_logs (1).txt](https://github.com/user-attachments/files/16741641/animetail_crash_logs.1.txt)
[animetail_crash_logs.txt](https://github.com/user-attachments/files/16741644/animetail_crash_logs.txt)

### Animetail version

0.16.5.7

### Android version

Android 13

### Device

Samsung galaxy tab s7

### Other details

I was facing the same crashing issue in kuukiyomi, animyomi works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Does this always happen to you?

**Comment by Billiamson** [comment]
Yes, to be honest I installed this app after crashing in kuukiyomi hoping it wouldn't have the same issue but for me it does. Going off what happened in kuuki, it was working at first but it started crashing about a week ago without any obvious changes/updates done by me as far as I can remember except for maybe an android security update. The same extensions that I use in animetail will work in aniyomi and dantotsu as well.

**Comment by Dark25** [comment]
> Yes, to be honest I installed this app after crashing in kuukiyomi hoping it wouldn't have the same issue but for me it does. Going off what happened in kuuki, it was working at first but it started crashing about a week ago without any obvious changes/updates done by me as far as I can remember except for maybe an android security update. The same extensions that I use in animetail will work in aniyomi and dantotsu as well.

disable cast if you use a huawei device

**Comment by Billiamson** [comment]
Reinstalling the app fixed the issue for me, no idea how it broke in the first place.
