### ISSUE TITLE
Able to Minimize player in PIP while loading

### ISSUE THREAD

**Issue by Brajesh3** [Animetailapp/Animetail#143]
### Describe your suggested feature

On the player screen
Two ways to go back 
1st is by guesture
2nd is by back button

When this setting is turned on
More > settings > player > (pip section) Automatically switch to pip mode on exiting the player

Any video that keeps loading or failing video player gets stuck. Can't go back by guesture or back button
You have stop the app from recent apps

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
already added
