### ISSUE TITLE
Differentiate Animetail2's README.md from Kuukiyomi for Unique Identity

### ISSUE THREAD

**Issue by Brajesh3** [Animetailapp/Animetail#148]
### Describe your suggested feature

Currently, Animetail's README.md is identical to Kuukiyomi's. As Animetail is a fork, it's important to differentiate it and highlight the unique features or objectives of this project. This will not only give Animetail its own identity but also help users understand the specific improvements or changes made in this fork.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
what do you think?

https://github.com/Dark25/Animetail2/commit/476e7b5374b07a18200f53d30493076ef69ae1fe

**Comment by Brajesh3** [comment]
One plus point 
Faster updates
