### ISSUE TITLE
Auto skip feature

### ISSUE THREAD

**Issue by ShoaibKhanali** [Animetailapp/Animetail#149]
### Describe your suggested feature

On websites like zoro.to( now aniwatch) there is a feature where intro and outro get auto skipped 

https://anime-skip.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
This already exists

![image](https://github.com/user-attachments/assets/5c18f307-6824-47e4-8dda-4a01ee54d13b)

**Comment by ShoaibKhanali** [comment]
My bad you are right.
