### ISSUE TITLE
Unable to download using External downloader

### ISSUE THREAD

**Issue by Hikari2w2** [Animetailapp/Animetail#152]
### Steps to reproduce

Look for a show
Click on download button to download an episode 
External Downloader pop up won't show up, instead I'm getting this error:
![Screenshot_2024-09-09-14-03-11-523-edit_com dark animetailv2](https://github.com/user-attachments/assets/7f85bee5-835b-43b6-88d2-8768b9743ac4)

### Expected behavior

Look for a show
Click on download button to download an episode 
External downloader pop up should show up to download the episode 

### Actual behavior

Can't toast on a thread that has not been called Looper.prepare()

### Animetail version

0.16.5.8

### Android version

11

### Device

Xiaomi 10C (MIU 13)

### Other details

Great fork, thanks for keeping alive de app ♥️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Fixed and now available in preview version

**Comment by Dark25** [comment]
Fixed and now available in preview version
