### ISSUE TITLE
App crashed when I tried to enable RPC

### ISSUE THREAD

**Issue by JinDevil-21** [Animetailapp/Animetail#162]
### Steps to reproduce

1. Connect my app with Discord by signing in
2. After pressing on rpc enable switch... App crashed
3. Kept on crashing after restarting multiple times 
4. Had to clear data to reuse it 

### Expected behavior

It should display my activity after I toggle on that switch 

### Actual behavior

It crashed after switching on
https://github.com/user-attachments/assets/ddefe65e-247c-41d3-ba7f-2aca4cda8cac

### Crash logs

[animetail_crash_logs.txt](https://github.com/user-attachments/files/17592124/animetail_crash_logs.txt)

### Animetail version

version 0.16.5.8-8834

### Android version

Android 14

### Device

Vivo V2334

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Give all necessary permissions to the app

**Comment by JinDevil-21** [comment]
> Give all necessary permissions to the app

Gave it all permission and file access 

https://chatgpt.com/share/672ee32c-2358-800d-8030-767f89495969

need to specify the foreground type for the discord rpc service

<service
    android:name=".data.connections.discord.DiscordRPCService"
    android:foregroundServiceType="mediaPlayback" />

**Comment by Dark25** [comment]
Fixed
