### ISSUE TITLE
Picture in picture bug

### ISSUE THREAD

**Issue by DarkPrincess00** [Animetailapp/Animetail#172]
### Steps to reproduce

1. Open any anime in picture in picture.
2. Then you go to open a manga.
3. Then when you go back to try to reopen the anime in picture in picture it won't let you. 

### Expected behavior

The anime should reopen in picture in picture mode. 

### Actual behavior

The anime couldn't open picture in picture mode. 

### Animetail version

Stable 0.16.5.8

### Android version

Android 13

### Device

Samsung z flod 2 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/dark25/animetail2/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
fixed
